### PR TITLE
Update guilds.php

### PR DESCRIPTION
**Pull request by glombers**
[#1168](https://otland.net/threads/znote-aac-1-4-tfs-0-2-13-tfs-0-3-6-0-4.166722/page-59#post-2468526)

### CODE REVIEW

**Comment by Raggaer** [comment]
Need server-side validation too?

**Comment by glombers** [comment]
https://otland.net/threads/znote-aac-1-4-tfs-0-2-13-tfs-0-3-6-0-4.166722/page-59#post-2468526
@Raggaer You can do it in block max characters?

**Comment by Znote** [comment]
As @Raggaer suggest, please add server-side validation here:
https://github.com/Znote/ZnoteAAC/blob/master/guilds.php#L116-L129
```php
if (strlen($_POST['guild_name']) < 31) {
 // Continue...
} else echo 'Guild name is to long. It has to be less than 30 characters..';
```

**Comment by glombers** [comment]
enter image description here

**Pull request merged**
