### PR TITLE
Fix admin_shop.php

### PR DESCRIPTION
**Pull request by gregorecruzeiro**
Notice: Undefined index: points in admin_shop.php on line 61

### CODE REVIEW

**Comment by Znote** [comment]
Isn't that a duplicate of line 7?

I think the actual problem is the foreach statement? Do you have an empty orders array?

Instead of 
```php
<?php foreach(($orders ? $orders : array()) as $order) { ?>
```

Try to do: 
```php
<?php foreach(($orders as $order) { ?>
```

But as an addition, wrap the entire `<table>` code with:
```php
<?php if ($orders !== false): ?>
  <table>
    code ...  
  </table>
<?php endif; ?>
```

This should hide the table if there are no rows in it.

**Comment by gregorecruzeiro** [comment]
In fact, the column <th> points </ th> is in the **znote_shop_logs table** and not in **znote_shop_orders**, it was not duplicate line 7, changed from **znote_shop_orders** to **znote_shop_logs**

**Comment by Znote** [comment]
Ahh wops. x) I'm tired. Thanks for the pull request. 👍

**Comment by gregorecruzeiro** [comment]
;p

**Pull request merged**
