### PR TITLE
Enable local SSL certificate verification

### PR DESCRIPTION
**Pull request by slawkens**
This fixes points being not delivered on same systems.

Also set the CURLOPT_SSLVERSION as stated here https://www.php.net/manual/de/function.curl-setopt.php#118536

### CODE REVIEW

**Comment by Znote** [comment]
Awesome, thanks. :)

**Comment by divinity76** [comment]
... unless you want to update it every couple of days, that should not be bundled in the git repo itself, it should be downloaded from a trusted source during installation, like https://curl.haxx.se/docs/caextract.html

unless you automate updating the repo version, the repo bundled cacert is certainly going to be out of date within days

**Comment by slawkens** [comment]
but do PayPal update their certificate every couple of days? I think it will last longer, won't it?

**Comment by divinity76** [comment]
@slawkens paypal does indeed use long-lasting certificates, the 1 they use for paypal.com right now is valid for 2 years (from "Tuesday, August 14, 2018" until "Tuesday, August 18, 2020")

.. still this is something that should be fetched during installation, not bundled with the git repo, imo.

**Comment by Znote** [comment]
Sounds like a github wiki page could be useful here

**Pull request merged**
